# Qwen3.5-4B: local loading experiment

Load the exact competition model `Qwen/Qwen3.5-4B` with **4-bit NF4 weights** on the local RTX 4060 (8 GB). This is a quantized development configuration, not a reproduction of full-precision robustness labels.

From the repository root:
```bash
bash scripts/install_fast_kernels.sh
uv run python -m ipykernel install --user --name aimo-interp-uv --display-name "AIMO Interp (uv)"
```
Select **AIMO Interp (uv)** as the notebook kernel. The first load downloads weights into the ignored `data/huggingface` directory; later loads reuse them. Run cells in order. Restart the kernel to release the model's GPU memory.

[Official model card](https://huggingface.co/Qwen/Qwen3.5-4B) · [Quantization documentation](https://huggingface.co/docs/transformers/quantization/bitsandbytes)


If loading appears stuck, the weight progress bar and a Python stack dump after 60 seconds help locate the wait. Loading uses the already downloaded cache without network requests. Do not rerun the loading cell while a model is resident; restart the kernel first. Generation uses `stream=False` for timing; the complete response is printed after generation finishes.


The setup script installs Flash Linear Attention and builds `causal-conv1d` using uv-managed CUDA tools. Restart the notebook kernel after installation so Transformers detects them. Loading prints `DeltaNet fast path: True` when both optimized kernels are available. The first inference may take longer while Triton compiles kernels.

In [1]:
from pathlib import Path
import sys
import importlib.metadata
from functools import partial

REPO_ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").is_file())
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from aimo_interp.model import CACHE_DIR, MODEL_ID, REVISION, load_model, solve as generate_response
import torch

assert Path(sys.prefix).resolve() == (REPO_ROOT / ".venv").resolve(), "Select the repository's uv kernel."
assert torch.cuda.is_available(), "A CUDA GPU is required for this notebook."
print("Python:", sys.executable)
for package in ["torch", "transformers", "accelerate", "bitsandbytes"]:
    print(f"{package}: {importlib.metadata.version(package)}")
print("GPU:", torch.cuda.get_device_name(0))
free, total = torch.cuda.mem_get_info()
print(f"VRAM: {free / 2**30:.2f} GiB free / {total / 2**30:.2f} GiB total")
print("Model cache:", CACHE_DIR)

/home/suhas-shankar/Projects/AI_Research/AIMO_Interp/aimo-interp-investigate-black-box/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Python: /home/suhas-shankar/Projects/AI_Research/AIMO_Interp/aimo-interp-investigate-black-box/.venv/bin/python
torch: 2.12.1
transformers: 5.13.0
accelerate: 1.13.0
bitsandbytes: 0.50.2
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
VRAM: 7.51 GiB free / 7.62 GiB total
Model cache: /home/suhas-shankar/Projects/AI_Research/AIMO_Interp/aimo-interp-investigate-black-box/data/huggingface

Model loading, cast-warning filtering, and prompt scaffolding are defined in `../src/aimo_interp/model.py`.

In [2]:
QUANTIZATION_BITS = 4  # NF4 with double quantization; restart the kernel before switching.
COMPUTE_DTYPE = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

In [3]:
if "model" in globals():
    raise RuntimeError("Model already loaded. Reuse it, or restart the kernel before loading again.")

model, tokenizer = load_model(
    quantization_bits=QUANTIZATION_BITS,
    compute_dtype=COMPUTE_DTYPE,
)

{'model': 'Qwen/Qwen3.5-4B', 'revision': '851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a', 'quantization_bits': 4, 'compute_dtype': 'torch.bfloat16'}
DeltaNet fast path: True
Loading tokenizer...
Loading and quantizing weights on GPU...

Loading weights: 100%|██████████| 723/723 [00:02<00:00, 267.04it/s]

Loaded in 3.5 seconds
Model footprint: 3.01 GiB
CUDA allocated: 3.08 GiB
Parameter devices: ['cuda:0']

## Short generation check

Use a single instruction asking for a boxed final answer, appended to the unchanged problem. `solve()` retains thinking by default for mathematical experiments. The simple 2 + 2 formatting check explicitly disables thinking to isolate output formatting. It is not a competition-model robustness evaluation.

Streaming is disabled for timing. Rerun the math generation cell after the first inference to measure warmed-up performance; timing includes prompt processing. `hit_token_limit=True` indicates possible truncation; inspect whether a final answer was actually produced. Greedy decoding remains a local development setting rather than the organizers' sampled evaluation protocol.

In [4]:
# Reload the helper without reloading the model already on the GPU.
import importlib
from aimo_interp import model as model_module

importlib.reload(model_module)
solve = partial(model_module.solve, model=model, tokenizer=tokenizer)

# Formatting smoke test only; real math runs retain thinking by default.
result = solve("What is 2 + 2?", max_new_tokens=128, enable_thinking=False, stream=False)
print({key: value for key, value in result.items() if key != "response"})
print(result["response"])

Generating...
{'generated_tokens': 32, 'hit_token_limit': False, 'elapsed_seconds': 1.89, 'tokens_per_second': 16.95, 'peak_allocated_gib': 3.13}
The problem asks for the sum of 2 and 2.

$$2 + 2 = 4$$

\boxed{4}

## Non-robust Qwen cases from train-main-v2

These cells can run independently of the GPU/model-loading cells above.

We pin `aimo-interp/train-main-v2` to revision `23791d9b120132087877b0459f953d5959fc8455`. Filter the exact competition model and **explicit False labels**, preserving null labels in the full table. `max_drop` is the largest accuracy decrease across perturbation families, expressed as a fraction: 0.27 means 27 percentage points.

The dataset contains original problems and aggregate robustness metadata, not the perturbations, reference answers, or model solutions. These organizer labels refer to the evaluated model configuration; they do not establish robustness of our locally quantized checkpoint. A correct answer to an original problem alone does not reproduce its robustness label.

[Dataset card at this revision](https://huggingface.co/datasets/aimo-interp/train-main-v2/blob/23791d9b120132087877b0459f953d5959fc8455/README.md)


Download once from the repository root:
```bash
uv run scripts/download_train_main_v2.py
```
The cells below read `data/train-main-v2/data/train-00000-of-00001.parquet` without downloading data.

In [5]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display, Markdown

DATASET_ID = "aimo-interp/train-main-v2"
DATASET_REVISION = "23791d9b120132087877b0459f953d5959fc8455"
DATASET_MODEL_ID = "Qwen/Qwen3.5-4B"
repo_root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").is_file())
dataset_dir = repo_root / "data" / "train-main-v2"
dataset_path = dataset_dir / "data" / "train-00000-of-00001.parquet"
if not dataset_path.is_file():
    raise FileNotFoundError("Run `uv run scripts/download_train_main_v2.py` from the repository root first.")
provenance = json.loads((dataset_dir / "metadata.json").read_text())
if provenance["dataset"] != DATASET_ID or provenance["revision"] != DATASET_REVISION:
    raise ValueError("Dataset revision mismatch. Download the pinned revision with the script.")
train_main_v2 = pd.read_parquet(dataset_path)
train_main_v2.index.name = "dataset_row"  # Positional row, not an official case ID.
qwen_cases = train_main_v2.loc[train_main_v2["model_id"].eq(DATASET_MODEL_ID)].copy()
# Nullable BooleanDtype ensures null labels stay null rather than becoming False.
qwen_cases["is_robust"] = qwen_cases["is_robust"].astype("boolean")
qwen_non_robust = qwen_cases.loc[qwen_cases["is_robust"].eq(False).fillna(False)].copy()
print(f"Dataset: {DATASET_ID}@{DATASET_REVISION}")
print(f"Total dataset rows: {len(train_main_v2)}; Qwen rows: {len(qwen_cases)}")
print(f"Qwen: {qwen_cases['is_robust'].sum()} robust, {len(qwen_non_robust)} non-robust, "
      f"{qwen_cases['is_robust'].isna().sum()} unlabeled")
display(qwen_non_robust[["model_id", "reasoning_effort", "is_robust", "max_drop"]])

Dataset: aimo-interp/train-main-v2@23791d9b120132087877b0459f953d5959fc8455
Total dataset rows: 82; Qwen rows: 14
Qwen: 8 robust, 4 non-robust, 2 unlabeled

                    model_id reasoning_effort  is_robust  max_drop
dataset_row
10           Qwen/Qwen3.5-4B          default      False      0.27
11           Qwen/Qwen3.5-4B          default      False      0.27
12           Qwen/Qwen3.5-4B          default      False      0.40
13           Qwen/Qwen3.5-4B          default      False      0.68

In [6]:
for row_index, case in qwen_non_robust.iterrows():
    display(Markdown(
        f"### Dataset row {row_index} — max drop {case['max_drop']:.0%}\n\n"
        f"Model: `{case['model_id']}` · Effort: `{case['reasoning_effort']}` · "
        f"Label: **non-robust**\n\n" + case["problem"]
    ))

### Dataset row 10 — max drop 27%

Model: `Qwen/Qwen3.5-4B` · Effort: `default` · Label: **non-robust**

Let $S$ denote the value of the infinite sum
\[
\frac{1}{9} + \frac{1}{99} + \frac{1}{999} + \frac{1}{9999}  + \cdots
\]
Find the remainder when the greatest integer less than or equal to $10^{100} S$ is divided by $1000.$

### Dataset row 11 — max drop 27%

Model: `Qwen/Qwen3.5-4B` · Effort: `default` · Label: **non-robust**

Define a function $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ by
\begin{equation*}
    f(n) = \sum_{i = 1}^n \sum_{j = 1}^n j^{3272} \left\lfloor\frac1j + \frac{n-i}{n}\right\rfloor.
\end{equation*}
Let $M=2 \cdot 3 \cdot 5 \cdot 7 \cdot 11 \cdot 13$ and let $N = f{\left(M^{7}\right)} - f{\left(M^{7}-1\right)}$. Let $k$ be the largest non-negative integer such that $2^k$ divides $N$. What is the remainder when $2^k$ is divided by $20^3$?

### Dataset row 12 — max drop 40%

Model: `Qwen/Qwen3.5-4B` · Effort: `default` · Label: **non-robust**

Let $N$ be the number of positive integer divisors of $17017^{17}$ that leave a remainder of $5$ when divided by $12$. Find $N$.

### Dataset row 13 — max drop 68%

Model: `Qwen/Qwen3.5-4B` · Effort: `default` · Label: **non-robust**

Let $f \colon \mathbb{Z}_{\geq 1} \to \mathbb{Z}_{\geq 1}$ be a function such that for all positive integers $m$ and $n$,
\begin{equation*}
    f(m) + f(n) = f(m + n + mn).
\end{equation*}
Across all functions $f$ such that $f(n) \leq 617$ for all $n \leq 617$, how many different values can $f(3520)$ take?

In [7]:
import pandas as pd
train_df = pd.read_parquet(REPO_ROOT / "data_artifacts/train-main-v2/train_allowed.parquet")

In [8]:
df1 = train_df[train_df["model_id"] == "Qwen/Qwen3.5-4B"]

In [9]:
df1

,model_id,reasoning_effort,problem,is_robust,max_drop
0,Qwen/Qwen3.5-4B,default,The Fibonacci numbers are defined as follows: ...,True,-0.01
1,Qwen/Qwen3.5-4B,default,Find the sum of all real numbers $r$ such that...,True,0.01
2,Qwen/Qwen3.5-4B,default,An isosceles trapezoid has an inscribed circle...,True,0.01
3,Qwen/Qwen3.5-4B,default,Find the sum of all integer bases $b>9$ for wh...,True,0.04
4,Qwen/Qwen3.5-4B,default,Alice writes all positive integers from $1$ to...,None,0.11
5,Qwen/Qwen3.5-4B,default,Let $S$ denote the value of the infinite sum\n...,False,0.27
6,Qwen/Qwen3.5-4B,default,Let $N$ be the number of positive integer divi...,False,0.40

In [10]:
problem_statement = df1.iloc[6]["problem"]
problem_statement

'Let $N$ be the number of positive integer divisors of $17017^{17}$ that leave a remainder of $5$ when divided by $12$. Find $N$.'

In [11]:
# Run without streaming; rerun this cell to compare warmed-up timings.
result = solve(problem_statement, max_new_tokens=1024*8, stream=False)
print({key: value for key, value in result.items() if key != "response"})
print(result["response"])

Generating...
{'generated_tokens': 8192, 'hit_token_limit': True, 'elapsed_seconds': 273.16, 'tokens_per_second': 29.99, 'peak_allocated_gib': 3.38}
Let $n = 17017^{17}$. We want to find the number of positive integer divisors of $n$ that leave a remainder of $5$ when divided by $12$.
Let $d$ be a divisor of $n$. We are looking for the number of such $d$ such that $d \equiv 5 \pmod{12}$.
First, let's find the prime factorization of $17017$.
$17017$ is not divisible by 2 (odd).
Sum of digits is $1+7+0+1+7 = 16$, not divisible by 3.
Ends in 7, not divisible by 5.
$17017 = 17 \times 1001$.
$1001 = 7 \times 11 \times 13$.
So $17017 = 17 \times 7 \times 11 \times 13$.
Let's check: $17 \times 7 = 119$. $119 \times 11 = 1309$. $1309 \times 13 = 17017$. Correct.
So $17017 = 7 \times 11 \times 13 \times 17$.
The prime factors are 7, 11, 13, 17.
The number is $n = (7 \times 11 \times 13 \times 17)^{17} = 7^{17} \times 11^{17} \times 13^{17} \times 17^{17}$.
We are looking for divisors $d$ of $n$.
Let $d = 7^a \times 11^b \times 13^c \times 17^e$, where $0 \le a, b, c, e \le 17$.
We want $d \equiv 5 \pmod{12}$.
Let's analyze the condition $d \equiv 5 \pmod{12}$.
This means $d$ is odd (since 5 is odd) and $d \equiv 5 \pmod 3$ (since $5 \equiv 2 \pmod 3$) and $d \equiv 1 \pmod 4$ (since $5 \equiv 1 \pmod 4$).
Wait, $5 \equiv 1 \pmod 4$ and $5 \equiv 2 \pmod 3$.
Also $d$ must be coprime to 2, so $d$ is odd.
Since $d$ is a divisor of $n$, and $n$ is odd, all divisors $d$ are odd.
So the condition $d \equiv 5 \pmod{12}$ is equivalent to $d \equiv 5 \pmod 3$ and $d \equiv 1 \pmod 4$.
Wait, $5 \equiv 2 \pmod 3$.
Let's check the Chinese Remainder Theorem.
$x \equiv 1 \pmod 4$
$x \equiv 2 \pmod 3$
$x = 4k + 1$.
$4k + 1 \equiv 2 \pmod 3 \implies k + 1 \equiv 2 \pmod 3 \implies k \equiv 1 \pmod 3$.
So $k = 3m + 1$.
$x = 4(3m + 1) + 1 = 12m + 5$.
So $d \equiv 5 \pmod{12}$ is indeed the condition.
This implies $d \equiv 1 \pmod 4$ and $d \equiv 2 \pmod 3$.
Also $d$ must be odd.
Let's look at the prime factors of $d$.
$d = 7^a 11^b 13^c 17^e$.
We need to determine the possible values of $a, b, c, e$ such that $d \equiv 5 \pmod{12}$.
Let's look at the residues of the prime factors modulo 12.
$7 \equiv 7 \pmod{12}$.
$11 \equiv 11 \equiv -1 \pmod{12}$.
$13 \equiv 1 \pmod{12}$.
$17 \equiv 5 \pmod{12}$.

Let's denote the exponents as $a, b, c, e$.
$d \equiv 7^a \cdot 11^b \cdot 13^c \cdot 17^e \pmod{12}$.
We know $13 \equiv 1 \pmod{12}$, so $13^c \equiv 1^c \equiv 1 \pmod{12}$.
So $d \equiv 7^a \cdot 11^b \cdot 17^e \pmod{12}$.
We want $d \equiv 5 \pmod{12}$.
Let's analyze the powers of 7, 11, 17 modulo 12.
Powers of 7 mod 12:
$7^1 \equiv 7$
$7^2 = 49 \equiv 1$
$7^3 \equiv 7$
So $7^a \equiv 7$ if $a$ is odd, and $1$ if $a$ is even.
Powers of 11 mod 12:
$11 \equiv -1$.
$11^b \equiv (-1)^b$.
So $11^b \equiv 1$ if $b$ is even, and $-1 \equiv 11$ if $b$ is odd.
Powers of 17 mod 12:
$17 \equiv 5$.
$17^2 = 289$. $289 = 12 \times 24 + 1$. So $17^2 \equiv 1 \pmod{12}$.
$17^e \equiv 5$ if $e$ is odd, and $1$ if $e$ is even.

So we have $d \equiv 7^a \cdot (-1)^b \cdot 5^e \pmod{12}$.
We want $d \equiv 5 \pmod{12}$.
Let's list the possible values for $7^a \cdot (-1)^b \cdot 5^e \pmod{12}$.
The term $7^a$ can be $1$ or $7$.
The term $(-1)^b$ can be $1$ or $-1 \equiv 11$.
The term $5^e$ can be $1$ or $5$.

Let's check the combinations.
Case 1: $a$ is even ($7^a \equiv 1$).
Then $d \equiv 1 \cdot (-1)^b \cdot 5^e \pmod{12}$.
Subcase 1.1: $b$ is even ($(-1)^b \equiv 1$).
Then $d \equiv 1 \cdot 1 \cdot 5^e \equiv 5^e \pmod{12}$.
We need $5^e \equiv 5 \pmod{12}$.
This requires $e$ to be odd.
So if $a$ even, $b$ even, $e$ odd, then $d \equiv 5 \pmod{12}$.
Subcase 1.2: $b$ is odd ($(-1)^b \equiv 11$).
Then $d \equiv 1 \cdot 11 \cdot 5^e \pmod{12}$.
If $e$ is even, $d \equiv 11 \cdot 1 = 11 \not\equiv 5$.
If $e$ is odd, $d \equiv 11 \cdot 5 = 55 \equiv 5 \pmod{12}$.
So if $a$ even, $b$ odd, $e$ odd, then $d \equiv 5 \pmod{12}$.

Case 2: $a$ is odd ($7^a \equiv 7$).
Then $d \equiv 7 \cdot (-1)^b \cdot 5^e \pmod{12}$.
Subcase 2.1: $b$ is even ($(-1)^b \equiv 1$).
Then $d \equiv 7 \cdot 1 \cdot 5^e \pmod{12}$.
If $e$ is even, $d \equiv 7 \cdot 1 = 7 \not\equiv 5$.
If $e$ is odd, $d \equiv 7 \cdot 5 = 35 \equiv 11 \not\equiv 5$.
So no solution here.
Subcase 2.2: $b$ is odd ($(-1)^b \equiv 11$).
Then $d \equiv 7 \cdot 11 \cdot 5^e \pmod{12}$.
$7 \cdot 11 = 77 \equiv 5 \pmod{12}$.
So $d \equiv 5 \cdot 5^e \pmod{12}$.
If $e$ is even, $d \equiv 5 \cdot 1 = 5$.
If $e$ is odd, $d \equiv 5 \cdot 5 = 25 \equiv 1$.
So if $a$ odd, $b$ odd, $e$ even, then $d \equiv 5 \pmod{12}$.

Let's summarize the conditions on exponents $a, b, c, e$ (where $c$ doesn't affect the residue mod 12, but $c$ can be anything from 0 to 17).
The conditions are:
1. $a$ even, $b$ even, $e$ odd.
2. $a$ even, $b$ odd, $e$ odd.
3. $a$ odd, $b$ odd, $e$ even.

Wait, check the logic again.
We have $d \equiv 7^a \cdot 11^b \cdot 13^c \cdot 17^e \pmod{12}$.
$13^c \equiv 1$.
So $d \equiv 7^a \cdot 11^b \cdot 17^e \pmod{12}$.
Let's re-evaluate the products.
Possible values for $7^a \pmod{12}$: $\{1, 7\}$.
Possible values for $11^b \pmod{12}$: $\{1, 11\}$.
Possible values for $17^e \pmod{12}$: $\{1, 5\}$.

We want the product to be $5 \pmod{12}$.
Let $X = 7^a$, $Y = 11^b$, $Z = 17^e$.
We want $X Y Z \equiv 5 \pmod{12}$.
Possible values for $X$:
- $a$ even $\implies X=1$.
- $a$ odd $\implies X=7$.
Possible values for $Y$:
- $b$ even $\implies Y=1$.
- $b$ odd $\implies Y=11$.
Possible values for $Z$:
- $e$ even $\implies Z=1$.
- $e$ odd $\implies Z=5$.

Let's check all $2 \times 2 \times 2 = 8$ combinations of parities of $a, b, e$.
1. $a$ even, $b$ even, $e$ even: $1 \cdot 1 \cdot 1 = 1 \neq 5$.
2. $a$ even, $b$ even, $e$ odd: $1 \cdot 1 \cdot 5 = 5$. (Match)
3. $a$ even, $b$ odd, $e$ even: $1 \cdot 11 \cdot 1 = 11 \neq 5$.
4. $a$ even, $b$ odd, $e$ odd: $1 \cdot 11 \cdot 5 = 55 \equiv 5$. (Match)
5. $a$ odd, $b$ even, $e$ even: $7 \cdot 1 \cdot 1 = 7 \neq 5$.
6. $a$ odd, $b$ even, $e$ odd: $7 \cdot 1 \cdot 5 = 35 \equiv 11 \neq 5$.
7. $a$ odd, $b$ odd, $e$ even: $7 \cdot 11 \cdot 1 = 77 \equiv 5$. (Match)
8. $a$ odd, $b$ odd, $e$ odd: $7 \cdot 11 \cdot 5 = 385 \equiv 1 \neq 5$.

So the valid combinations of parities for $(a, b, e)$ are:
- (even, even, odd)
- (even, odd, odd)
- (odd, odd, even)

Let's denote $a \pmod 2$ as $a_2$, $b_2$, $e_2$.
The conditions are:
1. $a_2=0, b_2=0, e_2=1$
2. $a_2=0, b_2=1, e_2=1$
3. $a_2=1, b_2=1, e_2=0$

Notice that in all valid cases, $a_2 + b_2 + e_2 \equiv 1 \pmod 2$?
Case 1: $0+0+1 = 1$.
Case 2: $0+1+1 = 2 \equiv 0$. Wait.
Case 3: $1+1+0 = 2 \equiv 0$.
So no simple parity sum condition.
Let's check the number of solutions for each case.
The exponents $a, b, c, e$ can range from $0$ to $17$.
The number of choices for $a$ is 18.
The number of choices for $b$ is 18.
The number of choices for $c$ is 18.
The number of choices for $e$ is 18.
We need to count the number of tuples $(a, b, c, e)$ satisfying the conditions.
The condition on $c$ is that $c$ can be any integer from $0$ to $17$. There are 18 choices for $c$.
So $N = 18 \times (\text{number of valid } (a, b, e))$.

Let's count the number of valid $(a, b, e)$ tuples.
The range for $a$ is $\{0, 1, \dots, 17\}$.
The number of even integers in this range is 9 ($0, 2, \dots, 16$).
The number of odd integers in this range is 9 ($1, 3, \dots, 17$).
Wait, $17$ is odd.
So there are 9 even numbers and 9 odd numbers.
Let $N_{even} = 9$ and $N_{odd} = 9$.
Similarly for $b$ and $e$.

Let's count the number of valid tuples $(a, b, e)$.
Case 1: $a$ even, $b$ even, $e$ odd.
Number of choices = $N_{even} \times N_{even} \times N_{odd} = 9 \times 9 \times 9 = 729$.
Case 2: $a$ even, $b$ odd, $e$ odd.
Number of choices = $N_{even} \times N_{odd} \times N_{odd} = 9 \times 9 \times 9 = 729$.
Case 3: $a$ odd, $b$ odd, $e$ even.
Number of choices = $N_{odd} \times N_{odd} \times N_{even} = 9 \times 9 \times 9 = 729$.

Total number of valid $(a, b, e)$ tuples is $729 + 729 + 729 = 3 \times 729 = 2187$.
Wait, is this correct?
Let's double check the conditions.
We need $d \equiv 5 \pmod{12}$.
$d = 7^a 11^b 13^c 17^e$.
$13^c \equiv 1 \pmod{12}$.
So we need $7^a 11^b 17^e \equiv 5 \pmod{12}$.
Let's re-verify the modular arithmetic.
$7 \equiv 7$. $7^2 = 49 = 48 + 1 \equiv 1$.
$11 \equiv -1$. $11^b \equiv (-1)^b$.
$17 \equiv 5$. $17^2 = 289 = 24 \times 12 + 1 \equiv 1$. $17^e \equiv 5^e$.
Wait, $5^1 = 5$. $5^2 = 25 \equiv 1$. $5^3 \equiv 5$.
So $17^e \equiv 5$ if $e$ is odd, $1$ if $e$ is even.
This matches my previous analysis.

Let's re-verify the products.
1. $a$ even ($1$), $b$ even ($1$), $e$ odd ($5$). Product $1 \cdot 1 \cdot 5 = 5$. Correct.
2. $a$ even ($1$), $b$ odd ($11$), $e$ odd ($5$). Product $1 \cdot 11 \cdot 5 = 55 = 4 \times 12 + 7$? No.
$55 = 48 + 7$. So $55 \equiv 7 \pmod{12}$.
Wait. $55 / 12 = 4$ remainder $7$.
My previous calculation was $55 \equiv 5$. Let's check.
$12 \times 4 = 48$. $55 - 48 = 7$.
So $55 \equiv 7 \pmod{12}$.
So Case 2 is NOT a solution.
Let me re-calculate $7 \times 11 \times 5$.
$7 \times 11 = 77$. $77 = 6 \times 12 + 5$. So $77 \equiv 5$.
$77 \times 5 = 385$.
$385 / 12$: $12 \times 30 = 360$. $385 - 360 = 25$.
$25 = 2 \times 12 + 1$. So $385 \equiv 1 \pmod{12}$.
So Case 8 ($a$ odd, $b$ odd, $e$ odd) gives 1.
Let's re-calculate Case 2 again.
$a$ even, $b$ odd, $e$ odd.
$1 \cdot 11 \cdot 5 = 55 \equiv 7$.
So Case 2 is not a solution.
Let's re-calculate Case 3.
$a$ odd, $b$ odd, $e$ even.
$7 \cdot 11 \cdot 1 = 77 \equiv 5$.
So Case 3 is a solution.

Let's re-calculate Case 1.
$a$ even, $b$ even, $e$ odd.
$1 \cdot 1 \cdot 5 = 5$.
So Case 1 is a solution.

Let's re-calculate Case 5.
$a$ odd, $b$ even, $e$ even.
$7 \cdot 1 \cdot 1 = 7$. Not 5.
Case 6.
$a$ odd, $b$ even, $e$ odd.
$7 \cdot 1 \cdot 5 = 35$. $35 = 2 \times 12 + 11$. So $11$. Not 5.
Case 7.
$a$ odd, $b$ odd, $e$ even.
$7 \cdot 11 \cdot 1 = 77 \equiv 5$. Solution.
Case 8.
$a$ odd, $b$ odd, $e$ odd.
$7 \cdot 11 \cdot 5 = 385 \equiv 1$. Not 5.

So the valid cases are:
1. $a$ even, $b$ even, $e$ odd.
3. $a$ odd, $b$ odd, $e$ even.

Wait, did I miss any?
Let's check the table again.
$a$ even ($1$), $b$ even ($1$), $e$ even ($1$) $\to 1$.
$a$ even ($1$), $b$ even ($1$), $e$ odd ($5$) $\to 5$. (Valid)
$a$ even ($1$), $b$ odd ($11$), $e$ even ($1$) $\to 11$.
$a$ even ($1$), $b$ odd ($11$), $e$ odd ($5$) $\to 55 \equiv 7$.
$a$ odd ($7$), $b$ even ($1$), $e$ even ($1$) $\to 7$.
$a$ odd ($7$), $b$ even ($1$), $e$ odd ($5$) $\to 35 \equiv 11$.
$a$ odd ($7$), $b$ odd ($11$), $e$ even ($1$) $\to 77 \equiv 5$. (Valid)
$a$ odd ($7$), $b$ odd ($11$), $e$ odd ($5$) $\to 385 \equiv 1$.

So we have exactly two valid combinations of parities for $(a, b, e)$:
1. $a$ even, $b$ even, $e$ odd.
2. $a$ odd, $b$ odd, $e$ even.

Let's check if there are any other constraints.
$d$ must be a positive integer divisor.
$d = 7^a 11^b 13^c 17^e$.
Since $a, b, c, e \ge 0$, $d$ is always a positive integer.
The condition $d \equiv 5 \pmod{12}$ is satisfied if and only if the parities match the valid cases.
Wait, is it possible that $d$ is not coprime to 12?
$d$ is a divisor of $17017^{17}$.
$17017 = 7 \times 11 \times 13 \times 17$.
The prime factors are 7, 11, 13, 17.
None of these are 2 or 3.
So $d$ is coprime to 2 and 3.
So $d$ is coprime to 12.
This means $d \pmod{12}$ must be in $\{1, 5, 7, 11\}$.
We are looking for $d \equiv 5 \pmod{12}$.
So $d$ is coprime to 12.
This is consistent with $d$ being odd and not divisible by 3.
$7 \equiv 1 \pmod 3$, $11 \equiv 2 \pmod 3$, $13 \equiv 1 \pmod 3$, $17 \equiv 2 \pmod 3$.
Wait, $11 \equiv 2 \pmod 3$.
If $b$ is odd, $11^b \equiv 2^b \equiv 2 \pmod 3$.
If $b$ is even, $11^b \equiv 1 \pmod 3$.
$7 \equiv 1 \pmod 3$.
$13 \equiv 1 \pmod 3$.
$17 \equiv 2 \pmod 3$.
So $d \equiv 1^a \cdot 2^b \cdot 1^c \cdot 2^e \pmod 3$.
$d \equiv 2^{b+e} \pmod 3$.
We want $d \equiv 5 \equiv 2 \pmod 3$.
So we need $2^{b+e} \equiv 2 \pmod 3$.
This implies $b+e$ must be odd.
Let's check our valid cases.
Case 1: $a$ even, $b$ even, $e$ odd.
$b$ even $\implies b \equiv 0 \pmod 2$. $e$ odd $\implies e \equiv 1 \pmod 2$.
$b+e$ is odd. This works.
Case 2: $a$ odd, $b$ odd, $e$ even.
$b$ odd, $e$ even. $b+e$ is odd. This works.
What about the other cases?
Case 3: $a$ even, $b$ odd, $e$ odd.
$b$ odd, $e$ odd. $b+e$ is even. $2^{even} \equiv 1 \pmod 3$.
So $d \equiv 1 \pmod 3$.
But we need $d \equiv 5 \equiv 2 \pmod 3$.
So $d \equiv 1 \pmod 3$ is not $5 \pmod 3$.
Wait, $5 \equiv 2 \pmod 3$.
So $d \equiv 1 \pmod 3$ is not a solution.
Wait, my previous check for Case 2 ($a$ even, $b$ odd, $e$ odd) gave $d \equiv 7 \pmod{12}$.
$7 \equiv 1 \pmod 3$.
So indeed, $d \equiv 7 \pmod{12}$ is not $5 \pmod{12}$.
So the condition $b+e$ odd is necessary.
Is it sufficient?
We also need $d \equiv 1 \pmod 4$.
Let's check $d \pmod 4$.
$7 \equiv -1 \pmod 4$.
$11 \equiv -1 \pmod 4$.
$13 \equiv 1 \pmod 4$.
$17 \equiv 1 \pmod 4$.
So $d \equiv (-1)^a \cdot (-1)^b \cdot 1^c \cdot 1^e \pmod 4$.
$d \equiv (-1)^{a+b} \pmod 4$.
We want $d \equiv 1 \pmod 4$.
So we need $(-1)^{a+b} \equiv 1 \pmod 4$.
This implies $a+b$ must be even.
Let's check our valid cases.
Case 1: $a$ even, $b$ even. $a+b$ is even. Works.
Case 2: $a$ odd, $b$ odd. $a+b$ is even. Works.
Case 3: $a$ even, $b$ odd. $a+b$ is odd. $d \equiv -1 \equiv 3 \pmod 4$.
$3 \not\equiv 1 \pmod 4$.
So Case 3 is not a solution.
Wait, my previous check for Case 3 ($a$ odd, $b$ odd, $e$ even) gave $d \equiv 5 \pmod{12}$.
Let's re-verify Case 3.
$a$ odd, $b$ odd, $e$ even.
$a$ odd $\implies 7^a \equiv 7 \pmod{12}$.
$b$ odd $\implies 11^b \equiv 11 \pmod{12}$.
$e$ even $\implies 17^e \equiv 1 \pmod{12}$.
Product $7 \times 11 \times 1 = 77 \equiv 5 \pmod{12}$.
So Case 3 is a valid solution.
Wait, let's check $a+b$ parity for Case 3.
$a$ odd, $b$ odd $\implies a+b$ is even.
So $d \equiv 1 \pmod 4$.
And $b$ odd, $e$ even $\implies b+e$ is odd.
So $d \equiv 2 \pmod 3$.
So $d \equiv 5 \pmod{12}$.
So Case 3 is indeed a valid solution.
Wait, I listed Case 3 as "a odd, b odd, e even" in my summary.
Let's re-list the cases I found earlier.
1. $a$ even, $b$ even, $e$ odd.
   - $a+b$ even $\implies d \equiv 1 \pmod 4$.
   - $b+e$ odd $\implies d \equiv 2 \pmod 3$.
   - $d \equiv 5 \pmod{12}$.
   - Valid.
2. $a$ odd, $b$ odd, $e$ even.
   - $a+b$ even $\implies d \equiv 1 \pmod 4$.
   - $b+e$ odd $\implies d \equiv 2 \pmod 3$.
   - $d \equiv 5 \pmod{12}$.
   - Valid.
3. $a$ even, $b$ odd, $e$ odd.
   - $a+b$ odd $\implies d \equiv 3 \pmod 4$.
   - $b+e$ even $\implies d \equiv 1 \pmod 3$.
   - $d \equiv 11 \pmod{12}$.
   - Invalid.
4. $a$ odd, $b$ even, $e$ odd.
   - $a+b$ odd $\implies d \equiv 3 \pmod 4$.
   - $b+e$ odd $\implies d \equiv 2 \pmod 3$.
   - $d \equiv 11 \pmod{12}$? No.
   - $d \equiv 3 \times 2 = 6 \pmod{12}$? No, $d$ must be coprime to 12.
   - Wait, $d$ is a divisor of $n$. $n$ is coprime to 12. So $d$ is coprime to 12.
   - $d \equiv 3 \pmod 4$ is impossible for a divisor of $n$?
   - $n$ is odd, so $d$ is odd. $d \equiv 3 \pmod 4$ is possible.
   - But $d$ must be coprime to 3.
   - $d \equiv 3 \pmod 4$ and $d \equiv 1 \pmod 3$?
   - $x \equiv 3 \pmod 4 \implies x \in \{3, 7, 11, 15, \dots\}$.
   - $x \equiv 1 \pmod 3 \implies x \in \{1, 4, 7, 10, 13, \dots\}$.
   - Intersection: $7, 19, \dots$.
   - $7 \equiv 7 \pmod{12}$.
   - $19 \equiv 7 \pmod{12}$.
   - So $d \equiv 7 \pmod{12}$.
   - Let's check the product for Case 4: $a$ odd, $b$ even, $e$ odd.
   - $7^a \equiv 7$. $11^b \equiv 1$. $17^e \equiv 5$.
   - $7 \times 1 \times 5 = 35 \equiv 11 \pmod{12}$.
   - Wait, $35 = 2 \times 12 + 11$.
   - So $d \equiv 11 \pmod{12}$.
   - $11 \equiv 2 \pmod 3$.
   - $11 \equiv 3 \pmod 4$.
   - So $d \equiv 11 \pmod{12}$ is consistent with $d \equiv 3 \pmod 4$ and $d \equiv 2 \pmod 3$.
   - But we want $d \equiv 5 \pmod{12}$.
   - So Case 4 is invalid.

So the valid cases are indeed:
1. $a$ even, $b$ even, $e$ odd.
2. $a$ odd, $b$ odd, $e$ even.

Let's check if there are any other constraints.
We need $d \equiv 5 \pmod{12}$.
This is equivalent to $d \equiv 1 \pmod 4$ and $d \equiv 2 \pmod 3$.
$d \equiv 1 \pmod 4 \iff a+b$ is even.
$d \equiv 2 \pmod 3 \iff b+e$ is odd.
So we need:
$a+b \equiv 0 \pmod 2$
$b+e \equiv 1 \pmod 2$
This implies $a+e \equiv 1 \pmod 2$.
So $a$ and $e$ must have different parity.
Also $b$ must have the same parity as $a$ (since $a+b$ even).
So $b$ and $a$ have same parity.
So $a$ and $b$ have same parity, and $a$ and $e$ have different parity.
This means $b$ and $e$ have different parity.
Let's check the cases again.
Case 1: $a$ even, $b$ even, $e$ odd.
$a, b$ same (even). $a, e$ different. $b, e$ different.
This works.
Case 2: $a$ odd, $b$ odd, $e$ even.
$a, b$ same (odd). $a, e$ different. $b, e$ different.
This works.
Are there any other cases?
We need $a+b$ even and $b+e$ odd.
This implies $a$ and $b$ have same parity, and $b$ and $e$ have different parity.
So $a$ and $e$ have different parity.
So the valid configurations are:
- $a$ even, $b$ even, $e$ odd.
- $a$ odd, $b$ odd, $e$ even.
These are